[build]
buildCommand = "pnpm install && pnpm run build"

[deploy]
startCommand = "node build/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 100

[[volumes]]
name = "database"
mountPath = "/app/volumes/db"

[[volumes]]
name = "uploads"
mountPath = "/app/volumes/uploads"

[env]
NODE_ENV = "production"